export const cardData = [
    {
        id:1,
        backgroundColor:"#FFE9C5",
        src: "/bagsimage/golden.jpg",
        heading:"Mini bag golden stones",
        price:"$1,820.00",
        rating:5,
    },
    {
        id:2,
        backgroundColor:"#FFE9C5",
        src: "/bagsimage/silver.jpg",
        heading:"Mini bag silver stones",
        price:"$1,820.00",
        rating:3,
    },
    {
        id:3,
        backgroundColor:"#FFE9C5",
        src: "/bagsimage/blue.jpg",
        heading:"Clutch silver stone",
        price:"$1,820.00",
        rating:4,
    },
    {
        id:4,
        backgroundColor:"#FFE9C5",
        src: "/bagsimage/bag5.jpg",
        heading:"black & white leather",
        price:"$1,820.00",
        rating: 2,
    },
    {
        id:5,
        backgroundColor:"#FFE9C5",
        src: "/bagsimage/bag6.jpg",
        heading:"Mini bag brown",
        price:"$1,820.00",
        rating: 5,
    },
    {
        id:6,
        backgroundColor:"#FFE9C5",
        src: "/bagsimage/pink.jpg",
        heading:"Mini bag pink",
        price:"$1,820.00",
        rating: 4,
    },
]